### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#131]
Was resizing an animated target (plate rack).  Noticed shootoff getting a bit sluggish.  Saw 100% cpu usage.  Did not see mem usage before shootoff crashed.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in **call**
    return self.func(*args)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 166, in scale_region
    self._scale_region(event, c, is_polygon, is_image, region, 20)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 220, in _scale_region
    self.cache_image_frames(region, tags["_path"], width, height)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 230, in cache_image_frames
    frames.append(image.copy().resize((width,height), Image.NEAREST))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1334, in resize
    im = self.im.resize(size, resample)
MemoryError

**Comment by phrack** [comment]
This is an upstream bug. Unfortunately, just like damn near every one involving the canvas :-/. I really hope the JavaFX one is more stable.
