### ISSUE TITLE
Exception in Tkinter callback - GifImagePlugin

### ISSUE THREAD

**Issue by setuidloot** [phrack/ShootOFF-legacy#132]
I have an amazing ability to break things.  Resize plate rack to minimal horizontal size:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in **call**
    return self.func(_args)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 166, in scale_region
    self._scale_region(event, c, is_polygon, is_image, region, 20)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 220, in _scale_region
    self.cache_image_frames(region, tags["_path"], width, height)
  File "/home/ubuntu/ShootOFF/canvas_manager.py", line 233, in cache_image_frames
    image.seek(len(frames))
  File "/usr/lib/python2.7/dist-packages/PIL/GifImagePlugin.py", line 111, in seek
    self.fp.seek(self.__offset)
MemoryError
Exception in Tkinter callback
*_\* Error in `python': double free or corruption (!prev): 0x0000000002aaa5d0 ***
Aborted (core dumped)

Might be related to #131

**Comment by phrack** [comment]
Upstream bug in PIL.  PIL needs to fix it, and I am not motivated to get them to given that we are moving to JavaFX.
